list: $/wpjscc/flashjs/models/config/columns.yaml
modelClass: Wpjscc\Flashjs\Models\Config
title: Configs
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'wpjscc/flashjs/configs/update/:id'
